require_relative './logic/command'
require_relative './logic/look'
require_relative './logic/walk'
require_relative './logic/inventory'
require_relative './logic/pickup'
require_relative './logic/help'
